library(tidyverse)

theme_theathletic <- function(){
  theme_minimal() %+replace%
    theme(
          legend.position = "right", 
          panel.grid.minor = element_blank(),
          plot.background = element_rect(fill = "#141622"),
          panel.background = element_rect(fill = "#141622", 
                                colour = "#141622",
                                size = 2, 
                                linetype = "dashed"),
          panel.grid.major = element_line(size = 0.5, 
                                linetype = 'dashed',
                                colour = "gray30"),
          axis.title.x = element_text(size = 13, 
                            face = "bold", 
                            colour = "white", 
                            family = "Century Gothic",
                            margin = margin(0.5, 0, 0, 0, unit = "cm")),
          axis.title.y = element_text(size = 13, 
                            face = "bold", 
                            colour = "white", 
                            family = "Century Gothic",
                            angle = 90,
                            vjust = 2,
                            margin = margin(0, 0.5, 0, 0, unit = "cm")),
         axis.text.x = element_text(colour = "white"),
         axis.text.y = element_text(colour = "white"),
         plot.title = element_markdown(face = "bold", 
                              colour = "white", 
                              size = 15, 
                              family = "Century Gothic",
                              hjust = 0),
         plot.subtitle = element_text(colour = "white", 
                             family = "URWGeometricW03-Light", 
                             size = 10,
                             margin = margin(0.2, 0, 1, 0, unit = "cm"), hjust = 0),
         plot.caption = element_text(colour = "white", 
                            family = "URWGeometricW03-Light", 
                            size = 10,
                            margin = margin(1, 0, 0, 0, unit = "cm"), hjust = 1),
         plot.title.position = "plot",
         legend.title = element_text(colour = "white", 
                            family = "URWGeometricW03-Light", 
                            size = 14),
         legend.text = element_text(colour = "white", 
                           family = "URWGeometricW03-Light", 
                           size = 14),
         plot.margin = margin(0.5, 1, 0.5, 1, unit = "cm")
    )
}
